version: '3'

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -a

  format:
    desc: Format the code
    aliases: ["ruff"]
    cmds:
      - poetry run ruff format
      - poetry run ruff check --fix

  build:
    desc: Build the container image
    cmds:
      - podman build -t wacli .

  test:
    desc: Run tests
    cmds:
      - poetry run pytest
