prefix dcterms: <http://purl.org/dc/terms/>
prefix gndo: <https://d-nb.info/standards/elementset/gnd#>

select distinct ?idn {
    ?snapshot dcterms:isPartOf ?page .
    ?snapshot gndo:gndIdentifier ?idn .
}