CONSTRUCT {
    ?page foaf:primaryTopic ?topic;
        dc:title ?title;
        dcterms:medium rdact:1018 ;
        ?pp ?po .
    ?snapshot dcterms:isPartOf ?page ;
            dc:identifier ?identifier, ?idn ;
            wdrs:describedby ?description ;
            ?sp ?so .
    ?description dcterms:modified ?modification .
} WHERE {
    ?page foaf:primaryTopic ?topic;
        dc:title ?title;
        dcterms:medium rdact:1018 ;
        ?pp ?po .
    ?snapshot dcterms:isPartOf ?page ;
        dc:identifier ?identifier ;
        wdrs:describedby ?description ;
        ?sp ?so .
    ?description dcterms:modified ?modification .
    bind(SUBSTR(str(?identifier), 9) as ?idn)
}